// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kvstore.proto

#include "kvstore.pb.h"
#include "kvstore.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace kvstore {

static const char* KVStore_method_names[] = {
  "/kvstore.KVStore/MyMethod",
};

std::unique_ptr< KVStore::Stub> KVStore::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KVStore::Stub> stub(new KVStore::Stub(channel));
  return stub;
}

KVStore::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_MyMethod_(KVStore_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KVStore::Stub::MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::kvstore::MyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_MyMethod_, context, request, response);
}

void KVStore::Stub::experimental_async::MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_MyMethod_, context, request, response, std::move(f));
}

void KVStore::Stub::experimental_async::MyMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvstore::MyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_MyMethod_, context, request, response, std::move(f));
}

void KVStore::Stub::experimental_async::MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_MyMethod_, context, request, response, reactor);
}

void KVStore::Stub::experimental_async::MyMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvstore::MyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_MyMethod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvstore::MyResponse>* KVStore::Stub::AsyncMyMethodRaw(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvstore::MyResponse>::Create(channel_.get(), cq, rpcmethod_MyMethod_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kvstore::MyResponse>* KVStore::Stub::PrepareAsyncMyMethodRaw(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kvstore::MyResponse>::Create(channel_.get(), cq, rpcmethod_MyMethod_, context, request, false);
}

KVStore::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVStore_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVStore::Service, ::kvstore::MyRequest, ::kvstore::MyResponse>(
          std::mem_fn(&KVStore::Service::MyMethod), this)));
}

KVStore::Service::~Service() {
}

::grpc::Status KVStore::Service::MyMethod(::grpc::ServerContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace kvstore

