// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kvstore.proto
#ifndef GRPC_kvstore_2eproto__INCLUDED
#define GRPC_kvstore_2eproto__INCLUDED

#include "kvstore.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace kvstore {

class KVStore final {
 public:
  static constexpr char const* service_full_name() {
    return "kvstore.KVStore";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::kvstore::MyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kvstore::MyResponse>> AsyncMyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kvstore::MyResponse>>(AsyncMyMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kvstore::MyResponse>> PrepareAsyncMyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kvstore::MyResponse>>(PrepareAsyncMyMethodRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MyMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvstore::MyResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void MyMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvstore::MyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void MyMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvstore::MyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kvstore::MyResponse>* AsyncMyMethodRaw(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kvstore::MyResponse>* PrepareAsyncMyMethodRaw(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::kvstore::MyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kvstore::MyResponse>> AsyncMyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kvstore::MyResponse>>(AsyncMyMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kvstore::MyResponse>> PrepareAsyncMyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kvstore::MyResponse>>(PrepareAsyncMyMethodRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response, std::function<void(::grpc::Status)>) override;
      void MyMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvstore::MyResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void MyMethod(::grpc::ClientContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void MyMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvstore::MyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void MyMethod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kvstore::MyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::kvstore::MyResponse>* AsyncMyMethodRaw(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kvstore::MyResponse>* PrepareAsyncMyMethodRaw(::grpc::ClientContext* context, const ::kvstore::MyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MyMethod_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status MyMethod(::grpc::ServerContext* context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_MyMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MyMethod() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MyMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyMethod(::grpc::ServerContext* /*context*/, const ::kvstore::MyRequest* /*request*/, ::kvstore::MyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMyMethod(::grpc::ServerContext* context, ::kvstore::MyRequest* request, ::grpc::ServerAsyncResponseWriter< ::kvstore::MyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MyMethod<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_MyMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_MyMethod() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::kvstore::MyRequest, ::kvstore::MyResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::kvstore::MyRequest* request, ::kvstore::MyResponse* response) { return this->MyMethod(context, request, response); }));}
    void SetMessageAllocatorFor_MyMethod(
        ::grpc::experimental::MessageAllocator< ::kvstore::MyRequest, ::kvstore::MyResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::kvstore::MyRequest, ::kvstore::MyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_MyMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyMethod(::grpc::ServerContext* /*context*/, const ::kvstore::MyRequest* /*request*/, ::kvstore::MyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* MyMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::kvstore::MyRequest* /*request*/, ::kvstore::MyResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* MyMethod(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::kvstore::MyRequest* /*request*/, ::kvstore::MyResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_MyMethod<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_MyMethod<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MyMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MyMethod() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MyMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyMethod(::grpc::ServerContext* /*context*/, const ::kvstore::MyRequest* /*request*/, ::kvstore::MyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MyMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MyMethod() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MyMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyMethod(::grpc::ServerContext* /*context*/, const ::kvstore::MyRequest* /*request*/, ::kvstore::MyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMyMethod(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_MyMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_MyMethod() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->MyMethod(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_MyMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyMethod(::grpc::ServerContext* /*context*/, const ::kvstore::MyRequest* /*request*/, ::kvstore::MyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* MyMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* MyMethod(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MyMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_MyMethod() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::kvstore::MyRequest, ::kvstore::MyResponse>(std::bind(&WithStreamedUnaryMethod_MyMethod<BaseClass>::StreamedMyMethod, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_MyMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MyMethod(::grpc::ServerContext* /*context*/, const ::kvstore::MyRequest* /*request*/, ::kvstore::MyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMyMethod(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kvstore::MyRequest,::kvstore::MyResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_MyMethod<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_MyMethod<Service > StreamedService;
};

}  // namespace kvstore


#endif  // GRPC_kvstore_2eproto__INCLUDED
